---
# tasks file for new-role
- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  notify: start nginx
  become: true

- name: copy index
  become: true
  copy:
    src: ./files/index.html
    dest: /usr/share/nginx/html/index.html
    force: true
